sudo: required
services:
  - docker

before_install:
  - docker build -t sameerkamran/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sameerkamran/docker-react npm run test -- --coverage
